name : deploy serverless

on:
  push:
    branches:
      -main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:[20.x]
    steps: 
    - uses: actions/checkout@v2
    - name: use python ${{matrix.node-version}}
      uses: action/setup-node@v1
      with:
        node-version:${{matrix.node-version}}
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        AWS_SECRET_ACCESS_KEY_ID: ${{secrets. AWS_SECRET_ACCESS_KEY_ID}}
        AWS_ACCESS_KEY-ID: ${{secrets.AWS_ACCESS_KEY-ID}}




