name : Deploy Lambda

on:
  push:
    branches:
      -main

jobs:
  deploy:
    name: deploy
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:[20.x]
    steps: 
    - uses: actions/checkout@v2
    - name: use python ${{matrix.node-version}}
      uses: action/setup-node@v1
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v3
      with:
        node-version:${{matrix.node-version}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest

    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        AWS_SECRET_ACCESS_KEY_ID: ${{secrets. AWS_SECRET_ACCESS_KEY_ID}}
        AWS_ACCESS_KEY-ID: ${{secrets.AWS_ACCESS_KEY-ID}}




